dependabot_auto_merge_config:
  api_version: 0 # still feeling out the API. Experimental. This file is subject to change.
  auto_merge:
    - dependency: govuk_publishing_components
      allowed_semver_bumps:
        - patch
        - minor
    - dependency: rubocop-govuk
      allowed_semver_bumps:
        - patch
        - minor
