inherit_gem:
  rubocop-govuk:
    - config/default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - "actions-gem-cache/**/*"
    - "govuk-content-schemas/**/*"

Style/ClassVars:
  Enabled: false
