@startuml C4_GOVUK_Container_data_science
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

System_Boundary(data_science, "Data science"){
Container(govuk_knowledge_graph, "govuk-knowledge-graph", "optional technology", "")
Container(govuk_related_links_recommender, "govuk-related-links-recommender", "optional technology", "")
}

@enduml
