@startuml C4_GOVUK_Container_publishing_apps
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

System_Boundary(publishing_apps, "Publishing apps"){
Container(collections_publisher, "collections-publisher", "optional technology", "")
Container(contacts_admin, "contacts-admin", "optional technology", "")
Container(content_publisher, "content-publisher", "optional technology", "")
Container(content_tagger, "content-tagger", "optional technology", "")
Container(local_links_manager, "local-links-manager", "optional technology", "")
Container(manuals_publisher, "manuals-publisher", "optional technology", "")
Container(maslow, "maslow", "optional technology", "")
Container(publisher, "publisher", "optional technology", "")
Container(service_manual_publisher, "service-manual-publisher", "optional technology", "")
Container(short_url_manager, "short-url-manager", "optional technology", "")
Container(specialist_publisher, "specialist-publisher", "optional technology", "")
Container(travel_advice_publisher, "travel-advice-publisher", "optional technology", "")
Container(whitehall, "whitehall", "optional technology", "")
}
System(apis, "APIs", "Optional Description")
System(supporting_apps, "Supporting apps", "Optional Description")
System(frontend_apps, "Frontend apps", "Optional Description")
Person_Ext(publisher, "Publisher", "")
Person_Ext(public, "Public", "")
Rel_Up(collections_publisher, apis, " ")
Rel_Up(collections_publisher, supporting_apps, " ")
Rel_Down(publisher, collections_publisher, " ")
Rel_Up(contacts_admin, apis, " ")
Rel_Up(contacts_admin, supporting_apps, " ")
Rel_Up(content_publisher, supporting_apps, " ")
Rel_Up(content_tagger, apis, " ")
Rel_Up(content_tagger, supporting_apps, " ")
Rel_Down(publisher, content_tagger, " ")
Rel_Up(local_links_manager, supporting_apps, " ")
Rel_Up(local_links_manager, apis, " ")
Rel_Up(manuals_publisher, supporting_apps, " ")
Rel_Up(manuals_publisher, apis, " ")
Rel_Up(maslow, apis, " ")
Rel_Up(maslow, supporting_apps, " ")
Rel_Up(publisher, apis, " ")
Rel_Up(publisher, frontend_apps, " ")
Rel_Up(publisher, supporting_apps, " ")
Rel_Up(service_manual_publisher, frontend_apps, " ")
Rel_Up(service_manual_publisher, supporting_apps, " ")
Rel_Up(service_manual_publisher, apis, " ")
Rel_Up(specialist_publisher, supporting_apps, " ")
Rel_Up(specialist_publisher, apis, " ")
Rel_Up(travel_advice_publisher, supporting_apps, " ")
Rel_Up(travel_advice_publisher, apis, " ")
Rel_Up(whitehall, supporting_apps, " ")
Rel_Up(whitehall, frontend_apps, " ")
Rel_Up(whitehall, apis, " ")
Rel_Down(publisher, whitehall, " ")
Rel_Down(public, whitehall, " ")

@enduml
