@startuml C4_GOVUK_Container_specialist_apps
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

System_Boundary(specialist_apps, "Specialist apps"){
Container(govuk_coronavirus_business_volunteer_form, "govuk-coronavirus-business-volunteer-form", "optional technology", "")
Container(govuk_coronavirus_find_support, "govuk-coronavirus-find-support", "optional technology", "")
Container(govuk_coronavirus_vulnerable_people_form, "govuk-coronavirus-vulnerable-people-form", "optional technology", "")
}

@enduml
