@startuml C4_GOVUK_Container_utilities
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

System_Boundary(utilities, "Utilities"){
Container(blinkenjs, "blinkenjs", "optional technology", "")
Container(govuk_alert_tracker, "govuk-alert-tracker", "optional technology", "")
Container(govuk_content_schemas, "govuk-content-schemas", "optional technology", "")
Container(govuk_dependencies, "govuk-dependencies", "optional technology", "")
Container(govuk_display_screen, "govuk-display-screen", "optional technology", "")
Container(govuk_pact_broker, "govuk-pact-broker", "optional technology", "")
Container(govuk_zendesk_display_screen, "govuk-zendesk-display-screen", "optional technology", "")
Container(seal, "seal", "optional technology", "")
Container(side_by_side_browser, "side-by-side-browser", "optional technology", "")
Container(tech_docs_monitor, "tech-docs-monitor", "optional technology", "")
}

@enduml
