name: Dependabot auto-merge
on: 
  pull_request:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    # if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      # - name: Dependabot metadata
      #   id: metadata
      #   uses: dependabot/fetch-metadata@v1.1.1
      #   with: 
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        #- uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })