on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1

      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rake
      - run: bundle exec rubocop
