on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clone govuk-content-schemas
        uses: actions/checkout@v2
        with:
          repository: alphagov/govuk-content-schemas
          ref: deployed-to-production
          path: ./govuk-content-schemas
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v1
        with:
          path: actions-gem-cache/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - run: |
          bundle config path actions-gem-cache/bundle
          bundle install --jobs 4 --retry 3

      - run: bundle exec rake
        env:
          GOVUK_CONTENT_SCHEMAS_PATH: ./govuk-content-schemas
      - run: bundle exec rubocop
